defaultEnvironment: test
#defaultEnvironment: preprod

environments:
  test:
    envName: test
    appUrl: http://146.59.32.4/index.php/
    eTitle: TesterSii
    email: test@test.com
    firstName: Testfirstname
    lastName: Testlastname
    password: password
    birthDate: 02/20/1995
    address: Test 222
    city: Warszawa
    zipCode: 01-100
    orderHistoryUrl: http://146.59.32.4/index.php?controller=history

    searchValue: HUMMINGBIRD
    priceFilterLeft: 13
    priceFilterRight: 15
    cartProductsAmount: 3
    cartTestProduct: THE BEST IS YET POSTER


  preprod:
    envName: preprod
    appUrl: https://logback.qos.ch/
    eTitle: Logback Home

browser:
  browser: chrome
  browserAttachScreenshot: false
  headlessMode: false
  browserTimeout: 20